server:
  port: ${PORT:4000}

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

app:
  env:
    auth-service-base-url: ${AUTH_SERVICE_BASE_URL:http://localhost:9001}
    open-api-endpoints:
      - "/auth/sign-up"
      - "/auth/login"
      - "/auth/validate"


