server:
  port: ${PORT:4000}

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:${AUTH_SERVICE_PORT:9001}
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: account-service
          uri: http://account-service:${ACCOUNT_SERVICE_PORT:9004}
          predicates:
            - Path=/accounts/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: http://user-service:${USER_SERVICE_PORT:9005}
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

app:
  env:
    auth-service-base-url: ${AUTH_SERVICE_BASE_URL}
    open-api-endpoints:
      - "/auth/sign-up"
      - "/auth/login"
      - "/auth/validate"
      - "/auth/generate-otp"
      - "/auth/verify-otp"
