server:
  port: ${PORT:4000}

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

app:
  env:
    auth-service-base-url: ${AUTH_SERVICE_BASE_URL}
    open-api-endpoints:
      - "/auth/sign-up"
      - "/auth/login"
      - "/auth/validate"
      - "/auth/generate-otp"
      - "/auth/verify-otp"
